# secret-transform command-line arguments.
args:
  - -v=2

env: []
# - name: SOME_VAR
#   value: 'some value'

image:
  repository: ghcr.io/maelvls/secret-transform
  tag: "{{ $.Chart.Version }}"

# Resource requests for the deployed secret-transform Pod.
resources:
  requests:
    cpu: 100m
    memory: 50Mi

selectorLabels:
  app.kubernetes.io/name: '{{ include "secret-transform.name" $ }}'
  app.kubernetes.io/instance: "{{ $.Release.Name }}"

rbac:
  enabled: true
  namespaces: []
