# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

before:
  hooks:
    - helm package ./deploy/chart --version {{ trimprefix .Version "v"}} --app-version {{ .Version }}
    - '{{if .IsSnapshot}}echo SKIPPING: {{end}}helm push ./secret-transform-{{ trimprefix .Version "v"}}.tgz oci://ghcr.io/maelvls/charts'

builds:
  - env: ["CGO_ENABLED=0"]
    goos:
      - linux
    goarch:
      - amd64
      - arm64

kos:
  - repository: ghcr.io/maelvls/secret-transform
    tags:
      - "{{.Version}}"
      - latest
    bare: true
    preserve_import_paths: false
    platforms:
      - linux/amd64
      - linux/arm64
    # It isn't possible to set custom annotations with ko. That means that the
    # GitHub Package won't be showing as part of the secret-transform repo.
    # Ref: https://github.com/ko-build/ko/issues/1090
    # Why: https://docs.github.com/en/packages/learn-github-packages/connecting-a-repository-to-a-package
    # annotations:
    #   org.opencontainers.image.source: https://github.com/maelvls/secret-transform
    creation_time: "{{.CommitTimestamp}}"
    ko_data_creation_time: "{{.CommitTimestamp}}"

release:
  draft: true
  replace_existing_draft: true
  target_commitish: "{{ .Commit }}"
  footer: |
    ## Helm Chart

    The Helm chart can be used with:

    ```bash
    helm upgrade --install secret-transform -n secret-transform --create-namespace \
      oci://ghcr.io/maelvls/charts/secret-transform --version {{ trimprefix .Version "v" }}
    ```
