{{- if and .Values.rbac.enabled (eq (len .Values.rbac.namespaces) 0) -}}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{ include "secret-transform.name" . }}"
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["list", "watch", "update"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{ include "secret-transform.name" . }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "{{ include "secret-transform.name" . }}"
subjects:
  - kind: ServiceAccount
    name: {{ include "secret-transform.name" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
