name: Release

on:
  pull_request:
  push:
    tags:
      - "*"

jobs:
  goreleaser:
    permissions:
      contents: write
      packages: write
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
      - uses: actions/checkout@v4
      - uses: azure/setup-helm@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: go test ./... -v

      - name: Run go vet
        run: go vet ./...

      - name: Check formatting
        run: |
          diff=$(gofmt -d $(git ls-files '*.go'))
          if [ -n "$diff" ]; then
            echo "$diff"
            echo 'Go files are not properly formatted'
            exit 1
          fi

      - name: Run GoReleaser (PR)
        uses: goreleaser/goreleaser-action@v5
        if: ${{ !startsWith(github.ref, 'refs/tags') }}
        with:
          args: release --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run GoReleaser (Publish Release)
        uses: goreleaser/goreleaser-action@v5
        if: ${{ startsWith(github.ref , 'refs/tags') }}
        with:
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
